-- Çevre İzin ve Lisans Yönetmeliği EK-1 / EK-2 faaliyet/tesis listesi.
-- Önceden src/permitArticles.ts içinde statik (koda gömülü) olarak duruyordu;
-- ced_project_categories'teki gibi artık admin panelinden yönetilebilir olması
-- için veritabanı tablosuna taşındı. Mevzuat değiştiğinde kod değişikliği/deploy
-- gerekmeden admin panelinden madde eklenip çıkarılabilir.
--
-- consultant_clients.permit_stage / permit_articles kolonları zaten mevcuttu
-- (Çevre İzin/Lisans Kapsamı alanı); bu tablo sadece seçilebilir madde
-- havuzunu (EK-1/EK-2) sağlıyor, ced_project_categories'ten TAMAMEN BAĞIMSIZ.

CREATE TABLE IF NOT EXISTS public.environmental_permit_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    stage TEXT NOT NULL CHECK (stage IN ('ek1', 'ek2')),
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (stage, code)
);

ALTER TABLE public.environmental_permit_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view permit categories" ON public.environmental_permit_categories;
CREATE POLICY "Authenticated users can view permit categories"
ON public.environmental_permit_categories FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Admins manage permit categories" ON public.environmental_permit_categories;
CREATE POLICY "Admins manage permit categories"
ON public.environmental_permit_categories FOR ALL
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- ==========================================
-- EK-1: ÇEVRE İZNİNE TABİ FAALİYETLER/TESİSLER LİSTESİ
-- ==========================================
INSERT INTO public.environmental_permit_categories (stage, code, title, sort_order) VALUES
('ek1', '1.1', $$Toplam yakma sistemi ısıl gücü 100 MW ve daha fazla olan termik ve ısı santralleri$$, 1),
('ek1', '1.2.1', $$Toplam yakma sistemi ısıl gücü 100 MW ve daha fazla olan ve yakıt olarak katı, sıvı, gaz yakıt ve biyokütlenin kullanıldığı tesisler$$, 2),
('ek1', '1.2.2', $$Toplam yakma sistemi ısıl gücü 50 MW ve daha fazla olan ve yakıt olarak katı ve sıvı yanıcı maddelerin kullanıldığı tesisler$$, 3),
('ek1', '1.3', $$Toplam yakma sistemi ısıl gücü 100 MW ve daha fazla olan kombine çevrim, birleşik ısı güç santralleri, içten yanmalı motorlar, gaz türbinleri, jeneratörler$$, 4),
('ek1', '1.4', $$Nükleer güç santralleri$$, 5),
('ek1', '1.5', $$Katran, katran ürünleri ve doğal asfalt üretim ve işleme tesisleri$$, 6),
('ek1', '1.6', $$Parçalama yoluyla hidrokarbonlardan gaz yakıt üretim tesisleri$$, 7),
('ek1', '1.7.1', $$Ham petrol rafinerileri$$, 8),
('ek1', '1.7.2', $$Hammadde kapasitesi 500 ton/gün ve daha fazla olan taşkömürü ve/veya bitümlü maddeleri gazlaştırma ve/veya sıvılaştırma tesisleri$$, 9),
('ek1', '1.7.3', $$Doğalgaz sıvılaştırma ve/veya gazlaştırma tesisleri$$, 10),
('ek1', '1.8', $$Kok üretim tesisleri$$, 11),
('ek1', '1.9', $$500 ton/gün ve daha fazla ham petrol ve/veya 500.000 m3/gün ve daha fazla doğalgaz çıkarılması işlemleri$$, 12),
('ek1', '2.1', $$Entegre çimento üretim tesisleri ve/veya çimento klinkeri üretim tesisleri$$, 13),
('ek1', '2.2', $$Yakıt olarak petrol koku kullanan ve sönmemiş ürün üretim kapasitesi 250 ton/gün ve üzeri olan boksit, dolomit, alçıtaşı, kireçtaşı, kiselgur, magnezit, kuvars ve/veya şamot pişirme tesisleri$$, 14),
('ek1', '2.3', $$Asbestos ve asbestos içeren ürünlerin çıkarıldığı, üretildiği ve/veya işlendiği tesisler$$, 15),
('ek1', '2.4', $$Toplam eritme kapasitesi 300 ton/gün ve daha fazla olan cam, glasswool ve/veya cam elyaf üretim tesisleri$$, 16),
('ek1', '2.5', $$Üretim kapasitesi 300 ton/gün ve daha fazla olan seramik ve/veya porselen üretim tesisleri$$, 17),
('ek1', '3.1', $$Metal ve kükürt cevherlerinin kavrulması, ergitilmesi, sinterlemesi, peletlemesi işlemlerinden en az birini içeren tesisler$$, 18),
('ek1', '3.2', $$Cevherden demir ve/veya çelik üreten tesisler$$, 19),
('ek1', '3.3', $$Üretim kapasitesi 100 ton/gün ve daha fazla olan cevherden, konsantreden ve/veya ikincil hammaddeden demir içermeyen ham metal üretim tesisleri$$, 20),
('ek1', '3.4', $$Üretim kapasitesi 500 ton/gün ve daha fazla olan ham demir üretim tesisleri$$, 21),
('ek1', '3.5', $$Üretim kapasitesi 2.000 ton/gün ve daha fazla olan ikincil metal özelliğine sahip demir-çelik hammaddesinden çelik üreten tesisler$$, 22),
('ek1', '3.6', $$Üretim kapasitesi 50 ton/gün ve daha fazla olan demir dışı metallerin ergitildiği ve/veya döküldüğü tesisler$$, 23),
('ek1', '3.7.1', $$Sıcak Haddeleme: Üretim kapasitesi 5.000 ton/gün ve daha fazla olan demir ve/veya çeliğin haddelendiği tesisler$$, 24),
('ek1', '3.7.2', $$Sıcak Haddeleme: Üretim kapasitesi 250 ton/gün ve daha fazla olan demir dışı metallerin haddelendiği tesisler$$, 25),
('ek1', '3.8', $$Üretim kapasitesi 700 ton/gün ve daha fazla olan demir, temper ve/veya çelik dökümhaneleri$$, 26),
('ek1', '3.9', $$Üretim kapasitesi 5.000 adet/gün ve daha fazla olan kurşunlu akümülatör ve/veya hücre üretimi dahil olmak üzere endüstriyel akümülatör üretimi yapan tesisler$$, 27),
('ek1', '4.1.1', $$Toplam üretim kapasitesi 150 ton/gün ve daha fazla olan inorganik kimyasal maddelerin üretildiği tesisler$$, 28),
('ek1', '4.1.2', $$İnorganik gazların üretildiği tesisler$$, 29),
('ek1', '4.1.3', $$Üretim kapasitesi 50 ton/gün ve daha fazla olan azot, fosfor, potasyum bazlı ve/veya organik gübre üretim tesisleri$$, 30),
('ek1', '4.1.4', $$Toplam üretim kapasitesi 50 ton/gün ve daha fazla olan organik kimyasalların üretildiği tesisler ve/veya petrokimya tesisleri$$, 31),
('ek1', '4.2', $$Organik kimyasal maddelerin hammadde olarak kullanım kapasitesi 100 ton/gün ve daha fazla olan tesisler$$, 32),
('ek1', '4.3', $$Toplam üretim kapasitesi 3.000 ton/yıl ve daha fazla olan ve terbiye işlemlerinden en az birini içeren iplik, kumaş, halı ve benzeri fabrikaları$$, 33),
('ek1', '4.4', $$Üretim kapasitesi 2.000 ton/yıl ve daha fazla olan ham deri işleme tesisleri$$, 34),
('ek1', '4.5', $$Toplam üretim kapasitesi 100 ton/gün ve daha fazla olan boya, pigment, vernik, cila ve benzeri maddelerin üretildiği tesisler$$, 35),
('ek1', '5.1', $$Toplam organik çözücü içeriği 250 kg/saat ve daha fazla olan boya, cila ve benzeri maddelerle malzemelerin boyandığı, cilalandığı ve/veya kurutulduğu tesisler$$, 36),
('ek1', '5.2', $$Toplam organik çözücü içeriği 250 kg/saat ve daha fazla olan boya ve benzeri maddeler kullanarak malzemelerin döner baskı makinaları ile basıldığı ve/ve/veya kurutulduğu tesisler$$, 37),
('ek1', '5.3', $$Üretim kapasitesi 10.000 adet/yıl ve daha fazla olan motorlu taşıtların üretildiği ve/veya boyandığı tesisler$$, 38),
('ek1', '5.4', $$Üretim kapasitesi 1.000 adet/yıl ve daha fazla olan demiryolu taşıtlarının üretildiği ve/veya boyandığı tesisler$$, 39),
('ek1', '5.5', $$Motorlu hava taşıtlarının üretildiği ve/veya onarımının yapıldığı tesisler$$, 40),
('ek1', '6.1', $$Selüloz üretim tesisleri$$, 41),
('ek1', '6.2', $$Kereste ve/veya benzeri lifli maddelerden kâğıt hamuru üretim tesisleri$$, 42),
('ek1', '6.3', $$Toplam üretim kapasitesi 300 ton/gün ve daha fazla olan ve hammadde olarak hazır selüloz ve/veya kâğıt kullanarak her çeşit karton, kâğıt ve/veya mukavva üretimi yapan tesisler$$, 43),
('ek1', '7.1', $$Şeker üretim tesisleri$$, 44),
('ek1', '7.2', $$Üretim kapasitesi 30 ton/gün ve daha fazla olan zeytin işleme tesisleri$$, 45),
('ek1', '7.3.1', $$Yağlı tohum işleme kapasitesi 1.000 ton/gün ve daha fazla olan ham yağ üretim tesisleri$$, 46),
('ek1', '7.3.2', $$Üretim kapasitesi 200 ton/gün ve daha fazla olan bitkisel yağ rafinasyon tesisleri$$, 47),
('ek1', '7.4', $$Üretim kapasitesi 25.000 ton/yıl ve daha fazla olan maya üretim tesisleri$$, 48),
('ek1', '7.5', $$Üretim kapasitesi 50.000 m3/yıl ve daha fazla olan fermantasyon ile alkollü içecek üreten tesisler$$, 49),
('ek1', '7.6.1', $$Toplam 5.000 büyükbaş eşdeğeri ve daha fazla sayıda hayvan yetiştiriciliği yapan tesisler$$, 50),
('ek1', '7.6.2', $$Toplam 1000 baş ve daha fazla sayıda domuz besiciliği yapan tesisler$$, 51),
('ek1', '7.6.3', $$Toplam 60.000 adet tavuk eşdeğeri ve daha fazla sayıda kanatlı hayvan yetiştiriciliği yapan tesisler$$, 52),
('ek1', '7.7.1', $$Toplam 100 büyükbaş eşdeğeri/gün ve daha fazla hayvan kesiminin yapıldığı tesisler$$, 53),
('ek1', '7.7.2', $$Toplam 50.000 adet tavuk eşdeğeri/gün ve daha fazla kanatlı hayvan kesiminin yapıldığı tesisler$$, 54),
('ek1', '7.8', $$Hammadde kapasitesi 100.000 litre/gün ve daha fazla olan süt ürünleri üretim tesisleri$$, 55),
('ek1', '7.9', $$Üretim kapasitesi 100 ton/gün ve daha fazla olan, bitkisel ve/veya hayvansal ürünlerin işlendiği, konserve yapıldığı ve/veya ambalajlandığı tesisler$$, 56),
('ek1', '8.1.1', $$Tıbbi atık sterilizasyon tesisleri$$, 57),
('ek1', '8.1.2', $$Atık elektrikli ve elektronik eşya işleme tesisleri$$, 58),
('ek1', '8.1.3', $$Atıktan türetilmiş yakıt (ATY) hazırlama tesisleri$$, 59),
('ek1', '8.1.4', $$PCB arındırma tesisleri$$, 60),
('ek1', '8.1.5', $$Ömrünü tamamlamış araç geçici depolama tesisleri$$, 61),
('ek1', '8.1.6', $$Tehlikeli atık ön işlem tesisleri$$, 62),
('ek1', '8.1.7', $$Tehlikesiz atık ön işlem tesisleri$$, 63),
('ek1', '8.2.1', $$Biyobozunur atık geri kazanım tesisleri (Mekanik ayırma, Biyokurutma, Biyometanizasyon, Kompost)$$, 64),
('ek1', '8.2.2', $$Atık yağ rafinasyon tesisleri$$, 65),
('ek1', '8.2.3', $$Bitkisel atık yağ geri kazanım tesisleri$$, 66),
('ek1', '8.2.4', $$Atık pil ve akümülatör geri kazanım tesisleri$$, 67),
('ek1', '8.2.5', $$Ömrünü tamamlamış lastik geri kazanım tesisleri$$, 68),
('ek1', '8.2.6', $$Tehlikeli atık geri kazanım tesisleri$$, 69),
('ek1', '8.2.7.1', $$Geri kazanım: Kapasitesi 300 ton/gün ve üzeri kâğıt geri kazanım tesisleri$$, 70),
('ek1', '8.2.7.2', $$Geri kazanım: Kapasitesi 2.000 ton/gün ve üzeri metal geri kazanım/ergitme tesisleri$$, 71),
('ek1', '8.2.7.3', $$Diğer tehlikesiz atık geri kazanım tesisleri$$, 72),
('ek1', '8.2.8', $$İleri Termal İşlem Tesisi (Piroliz, Gazlaştırma vb.)$$, 73),
('ek1', '8.3.1.1', $$Düzenli Depolama I. Sınıf$$, 74),
('ek1', '8.3.1.2', $$Düzenli Depolama II. Sınıf$$, 75),
('ek1', '8.3.1.3', $$Düzenli Depolama III. Sınıf$$, 76),
('ek1', '8.3.2', $$Maden atığı bertaraf tesisleri$$, 77),
('ek1', '8.4.1', $$Atık yakma ve/veya beraber yakma tesisleri$$, 78),
('ek1', '8.4.2', $$Atık ara depolama tesisleri$$, 79),
('ek1', '8.4.3', $$Yeniden Kullanıma Hazırlama tesisleri$$, 80),
('ek1', '8.4.4', $$Atık elektrikli ve elektronik eşya yeniden kullanıma hazırlama tesisi$$, 81),
('ek1', '9.1.1', $$Sıvılaştırılmış petrol gazı depolama (Kapasite >= 10.000 m3)$$, 82),
('ek1', '9.1.2', $$Doğalgaz/LNG depolama (Kapasite >= 20.000 m3)$$, 83),
('ek1', '9.1.3', $$LPG tüp dolum işlemleri (Kapasite >= 200 ton/gün)$$, 84),
('ek1', '9.2.1', $$Ham petrol depolama (Kapasite >= 100.000 ton)$$, 85),
('ek1', '9.2.2', $$Akaryakıt depolama (Benzin, motorin vb. Kapasite >= 50.000 ton)$$, 86),
('ek1', '9.2.3', $$Organik kimyasal madde depolama (Kapasite >= 50.000 ton)$$, 87),
('ek1', '9.3', $$Akrilonitril depolama (Kapasite >= 2.000 ton)$$, 88),
('ek1', '10.1', $$Sanayilerin toplu olarak yer aldığı bölgelere ait ortak atıksu arıtma tesisleri$$, 89),
('ek1', '10.2', $$Kentsel/evsel atıksu arıtma (Kapasite >= 20.000 m3/gün)$$, 90);

-- ==========================================
-- EK-2: ÇEVRE İZİN VE LİSANSINA TABİ FAALİYETLER/TESİSLER LİSTESİ
-- ==========================================
INSERT INTO public.environmental_permit_categories (stage, code, title, sort_order) VALUES
('ek2', '1.1.1', $$Termik/Isı Santralleri: 1 MW - 100 MW arası katı/sıvı yakıtlı tesisler$$, 1),
('ek2', '1.1.2', $$Termik/Isı Santralleri: 2 MW - 100 MW arası gaz yakıtlı veya çok yakıtlı tesisler$$, 2),
('ek2', '1.2.1', $$Yakıt yakan tesisler: 1 MW - 100 MW arası katı, sıvı yakıt ve biyokütle yakan tesisler$$, 3),
('ek2', '1.2.2', $$Yakıt yakan tesisler: 2 MW - 100 MW arası gaz ve çok yakıtlı tesisler$$, 4),
('ek2', '1.2.3', $$Yakıt yakan tesisler: 1 MW - 50 MW arası katı/sıvı yanıcı madde yakan tesisler$$, 5),
('ek2', '1.3', $$Kombine çevrim, jeneratörler vb: 1 MW - 100 MW arası tesisler$$, 6),
('ek2', '1.4', $$Kömür gazlaştırma/sıvılaştırma tesisleri (10 ton/gün - 500 ton/gün)$$, 7),
('ek2', '1.5', $$500 ton/gün'den az ham petrol veya 500.000 m3/gün'den az doğalgaz çıkarılması$$, 8),
('ek2', '1.6', $$Kurulu gücü 5MWe ve üzerinde olan jeotermal enerji üretim tesisleri$$, 9),
('ek2', '2.1', $$Klinkerden çimento üreten ve/veya paketleyen tesisler$$, 10),
('ek2', '2.2', $$Petrol koku yakan kireç/dolomit vb. pişirme tesisleri (< 250 ton/gün)$$, 11),
('ek2', '2.3', $$Petrol koku dışı yakıt yakan kireç/dolomit vb. pişirme tesisleri$$, 12),
('ek2', '2.4', $$Kireç, alçı, talk, kil vb. öğütme, söndürme ve/veya paketleme tesisleri$$, 13),
('ek2', '2.5', $$Perlit, zeolit, şist ve/veya kil genleştirme tesisleri$$, 14),
('ek2', '2.6', $$Cam, cam elyaf ve/veya cam yünü üretimi (< 300 ton/gün)$$, 15),
('ek2', '2.7', $$Cam ve cam ürünlerini asitlerle parlatan ve/veya matlaştıran tesisler$$, 16),
('ek2', '2.8', $$Seramik ve/veya porselen üretimi (3 ton/gün - 300 ton/gün)$$, 17),
('ek2', '2.9', $$Tuğla, ateş tuğlası ve/veya kiremit üretimi (>= 75 ton/gün)$$, 18),
('ek2', '2.10', $$Mineral madde ergitme tesisleri (Hammadde >= 20 ton/gün)$$, 19),
('ek2', '2.11', $$Gazlı beton, beton elemanı, çimento esaslı levha üretim tesisleri$$, 20),
('ek2', '2.12', $$Hazır beton ve harç tesisleri (Kapasite >= 10 m3/saat)$$, 21),
('ek2', '2.13', $$Beton/çimento esaslı sıkıştırılmış şekilli malzeme üretimi (>= 5 ton/saat)$$, 22),
('ek2', '2.14', $$Asfalt plent tesisleri ve mineral malzeme katkılı bitüm tesisleri$$, 23),
('ek2', '2.15', $$Patlayıcı kullanılan maden ve/veya taş ocakları$$, 24),
('ek2', '2.16', $$Maden ocakları (Maden Kanunu I, II, IV, V Grup, Kapasite >= 150 ton/gün)$$, 25),
('ek2', '2.17', $$Maden kırma, eleme, öğütme tesisleri (Kapasite >= 150 ton/gün)$$, 26),
('ek2', '2.18', $$Mermer işleme tesisleri (Kapasite >= 25.000 ton/yıl)$$, 27),
('ek2', '2.19', $$Kömür ve/veya cevher hazırlama ve/veya zenginleştirme tesisleri$$, 28),
('ek2', '2.20', $$Tuz üretim tesisleri$$, 29),
('ek2', '3.1', $$Demir dışı ham metal üretimi (15 ton/gün - 100 ton/gün)$$, 30),
('ek2', '3.2', $$Ham demir üretimi (50 ton/gün - 500 ton/gün)$$, 31),
('ek2', '3.3', $$İkincil metalden çelik üreten tesisler (< 2.000 ton/gün)$$, 32),
('ek2', '3.4', $$Demir dışı metal ergitme/döküm tesisleri (100 kg/gün - 50 ton/gün)$$, 33),
('ek2', '3.5.1', $$Sıcak Haddeleme: Demir/çelik haddeleme (5 ton/gün - 5.000 ton/gün)$$, 34),
('ek2', '3.5.2', $$Sıcak Haddeleme: Demir dışı metal haddeleme (5 ton/gün - 250 ton/gün)$$, 35),
('ek2', '3.5.3', $$Haddelemesiz metal ısıl işlem fırınları (Kapasite >= 5 ton/gün)$$, 36),
('ek2', '3.6.1', $$Soğuk Haddeleme: Demir/çelik (Kapasite >= 10 ton/gün)$$, 37),
('ek2', '3.6.2', $$Soğuk Haddeleme: Demir dışı metal (Kapasite >= 5 ton/gün)$$, 38),
('ek2', '3.7', $$Demir, temper ve çelik dökümhaneleri (5 ton/gün - 700 ton/gün)$$, 39),
('ek2', '3.8', $$Kurşunlu akümülatör/hücre üretimi (< 5.000 adet/gün)$$, 40),
('ek2', '3.9', $$Metal/plastik yüzey elektrolitik veya kimyasal kaplama (Havuz Hacmi >= 5 m3)$$, 41),
('ek2', '3.10', $$Batarya ve/veya pil üreten tesisler$$, 42),
('ek2', '3.11', $$Metal kaplama (Kurşun, çinko vb ergitme/püskürtme, Kapasite >= 5 ton/gün)$$, 43),
('ek2', '3.12', $$Metallerin sıcak dövüldüğü tesisler (Pres gücü >= 100 ton)$$, 44),
('ek2', '3.13', $$Civata, çivi vb soğuk/sıcak şekillendirme metal üretimi (>= 10 ton/gün)$$, 45),
('ek2', '3.14', $$Patlayıcı madde ile detonasyonlu biçimlendirme ve kaynak işleri$$, 46),
('ek2', '3.15', $$Metal sac depolama deposu, tank, makina üretimi (Kapasite >= 3 ton/gün)$$, 47),
('ek2', '3.16', $$Çelik boru ve profil üretimi (Soğuk/sıcak şekillendirme)$$, 48),
('ek2', '3.17', $$Metal püskürtmeli temizleme, taşlama, zımparalama (>= 10 ton/gün)$$, 49),
('ek2', '3.18', $$Metal tozları ve pastaları üreten tesisler$$, 50),
('ek2', '3.19', $$Motorlu taşıtların motorlarının üretimi$$, 51),
('ek2', '3.20', $$Tersaneler (Gemi inşa/bakım-onarım veya >= 20 m yat/tekne inşa/bakım)$$, 52),
('ek2', '3.21', $$Uçak bakım ve/veya onarım tesisleri$$, 53),
('ek2', '3.22', $$Demiryolu ekipmanı üreten tesisler$$, 54),
('ek2', '3.23', $$Metallere sırlama, emaye, mineleme ve benzeri işlemler$$, 55),
('ek2', '3.24', $$Demir dışı metal oksit üretim tesisleri$$, 56),
('ek2', '4.1.1', $$İnorganik kimyasal madde üretimi (< 150 ton/gün)$$, 57),
('ek2', '4.1.2', $$Hidrometalürji/elektrometalürji ile metal üretimi$$, 58),
('ek2', '4.1.3', $$Kalsiyum karpit, bor, silisyum karpit vb inorganik madde üretimi$$, 59),
('ek2', '4.1.4', $$İnorganik halojenli bileşiklerin üretildiği tesisler$$, 60),
('ek2', '4.1.5', $$Asetilen gazı üretim tesisleri$$, 61),
('ek2', '4.1.6', $$Organik kimyasal/petrokimya üretimi (1 ton/gün - 50 ton/gün)$$, 62),
('ek2', '4.1.7', $$Organometalik bileşiklerin üretildiği tesisler$$, 63),
('ek2', '4.1.8.1', $$Polimer ve sentetik elyaf üretim tesisleri$$, 64),
('ek2', '4.1.8.2', $$Sentetik reçine üretim tesisleri$$, 65),
('ek2', '4.1.8.3', $$Sentetik kauçuk veya kauçuk hamuru üretim tesisleri$$, 66),
('ek2', '4.1.8.4', $$Selüloz nitrat ve selüloit üretim tesisleri$$, 67),
('ek2', '4.1.9', $$Yüzey aktif maddelerin üretildiği tesisler$$, 68),
('ek2', '4.1.10', $$Kauçuk vulkanize lastik üretimi (Kapasite >= 50 kg/saat)$$, 69),
('ek2', '4.1.11', $$Lastik rejenere eden tesisler (Hammadde >= 3 ton/gün)$$, 70),
('ek2', '4.1.12', $$Katran boyası ve boya ara ürünleri üretim tesisleri$$, 71),
('ek2', '4.1.13', $$Temizlik ve bakım ürünleri üretimi (Kapasite >= 2 ton/gün)$$, 72),
('ek2', '4.1.14', $$Azot, fosfor, potasyum ve organik gübre üretimi (< 50 ton/gün)$$, 73),
('ek2', '4.2', $$Organik kimyasal hammadde kullanımı (2 ton/gün - 100 ton/gün)$$, 74),
('ek2', '4.3', $$Bitki koruma, biyosidal ürün veya etken maddesi üretimi$$, 75),
('ek2', '4.4', $$Farmasotik (ilaç vb) ürünlerin üretildiği tesisler$$, 76),
('ek2', '4.5', $$Yağlayıcı maddeler, gres yağları üretimi$$, 77),
('ek2', '4.6', $$Karbon siyahı, sentetik grafit üretimi$$, 78),
('ek2', '4.7', $$Doğal/sentetik reçine bazlı ürün üretimi (Reçine kullanımı >= 25 kg/saat)$$, 79),
('ek2', '4.8', $$Boya, pigment, vernik üretimi (1 ton/gün - 100 ton/gün)$$, 80),
('ek2', '4.9', $$Sentetik kauçuk bazlı ürünler üreten tesisler$$, 81),
('ek2', '4.10', $$Nitroselüloz ile vernik, mürekkep vb üretimi$$, 82),
('ek2', '4.11', $$Sülfat terebentin yağı veya tall yağı üretimi/işlenmesi$$, 83),
('ek2', '4.12', $$Yapı ve ahşap koruma/yapıştırma maddeleri üretimi (Kapasite >= 1 ton/gün)$$, 84),
('ek2', '4.13', $$İplik, kumaş terbiye fabrikaları (< 3.000 ton/yıl)$$, 85),
('ek2', '4.14', $$Ham deri işleme tesisleri (< 2.000 ton/yıl)$$, 86),
('ek2', '4.15', $$Biyodizel üretim tesisleri (Kapasite >= 1 ton/gün)$$, 87),
('ek2', '4.16', $$Zifir üretim ve zift buharlaştırma tesisleri$$, 88),
('ek2', '4.17', $$Plastik hammaddeler kullanarak plastik ürünler üreten tesisler$$, 89),
('ek2', '4.18', $$Diğer kimyasalların işlendiği tanımlanmayan tesisler$$, 90),
('ek2', '5.1', $$Yüzey boyama/kurutma: Çözücü kullanımı (25 kg/saat - 250 kg/saat)$$, 91),
('ek2', '5.2', $$Döner baskı boyama/kurutma: Çözücü kullanımı (25 kg/saat - 250 kg/saat)$$, 92),
('ek2', '5.3', $$Reçineli emprenye/kaplama/doyurma vb. (Kullanım >= 25 kg/saat)$$, 93),
('ek2', '5.4', $$Motorlu taşıt üretimi/boyanması (500 adet/yıl - 10.000 adet/yıl)$$, 94),
('ek2', '5.5', $$Demiryolu taşıt üretimi/boyanması (< 1.000 adet/yıl)$$, 95),
('ek2', '5.6', $$Beyaz eşya üretimi (Kapasite >= 10 ton/gün)$$, 96),
('ek2', '5.7', $$Malzemelerin katran, bitüm vb sıcak kaplanması$$, 97),
('ek2', '5.8', $$Tellerin organik maddeyle izole edilmesi$$, 98),
('ek2', '5.9', $$Sıvı/doymamış polyester reçine işleme (Kapasite >= 500 kg/saat)$$, 99),
('ek2', '5.10', $$Furan, fenolik veya aminoplast reçinelerin işlenmesi (Hammadde >= 10 kg/saat)$$, 100),
('ek2', '5.11', $$Sentetik reçine kullanarak balata üretimi$$, 101),
('ek2', '5.12', $$Zımpara kağıdı, plakası üretimi (Organik çözücü/bağlayıcı ile)$$, 102),
('ek2', '5.13', $$Plastik genleştirme, hacim verme (Hammadde >= 1.000 kg/saat)$$, 103),
('ek2', '5.14', $$Elektrostatik toz boyama (Kullanım >= 50 kg/saat)$$, 104),
('ek2', '6.1', $$Parke, sunta vb levha üretimi (Kapasite >= 500 m3/yıl)$$, 105),
('ek2', '6.2', $$Ağaç işleme ve kereste üretimi (Kapasite >= 3.500 m3/yıl)$$, 106),
('ek2', '6.3', $$Mobilya/ahşap ürün üretimi (Kapasite >= 150.000 m2/yıl)$$, 107),
('ek2', '6.4', $$Karton, kâğıt, mukavva üretimi (Kapasite < 300 ton/gün)$$, 108),
('ek2', '7.1', $$Süt ürünleri üretimi (10.050 lt/gün - 100.000 lt/gün)$$, 109),
('ek2', '7.2', $$Suma ve/veya malt üretimi (Kapasite >= 1.000 m3/yıl)$$, 110),
('ek2', '7.3', $$Alkollü içecek fermantasyon üretimi (50 m3/yıl - 50.000 m3/yıl)$$, 111),
('ek2', '7.4', $$Alkolsüz içecek üretimi (Kapasite >= 50 m3/yıl)$$, 112),
('ek2', '7.5', $$Şekerleme, çikolata üretimi (Kapasite >= 5 ton/gün)$$, 113),
('ek2', '7.6', $$Hayvansal yağların ergitilmesi (Kapasite >= 30 kg/gün)$$, 114),
('ek2', '7.7', $$Hayvansal artıkların depolanması ve işlenmesi$$, 115),
('ek2', '7.8', $$Hayvan derisi/kılı depolama ve işleme$$, 116),
('ek2', '7.9', $$Balık yağı, balık unu depolama ve üretimi$$, 117),
('ek2', '7.10.1', $$Zeytin işleme (Kapasite 1 ton/gün - 30 ton/gün)$$, 118),
('ek2', '7.10.2', $$Zeytinyağı üretimi (Kapasite >= 30 ton/gün)$$, 119),
('ek2', '7.11.1', $$Bitkisel ham yağ üretimi (< 1.000 ton/gün)$$, 120),
('ek2', '7.11.2', $$Bitkisel yağ rafinasyonu (< 200 ton/gün)$$, 121),
('ek2', '7.12', $$Çay üretimi (Kapasite >= 100 kg/gün)$$, 122),
('ek2', '7.13', $$Maya üretimi (< 25.000 ton/yıl)$$, 123),
('ek2', '7.14', $$Süt tozu üretim tesisleri$$, 124),
('ek2', '7.15', $$Nişasta ve nişasta türevleri üretimi$$, 125),
('ek2', '7.16', $$Hayvan yemi/dışkısı kurutma tesisleri$$, 126),
('ek2', '7.17.1', $$Büyükbaş hayvancılık (500 büyükbaş - 5.000 büyükbaş)$$, 127),
('ek2', '7.17.2', $$Domuz besiciliği (< 1.000 baş)$$, 128),
('ek2', '7.17.3', $$Kanatlı hayvancılık (20.000 tavuk - 60.000 tavuk)$$, 129),
('ek2', '7.18', $$Sıvı yumurta üretimi (Kapasite >= 10 ton/gün)$$, 130),
('ek2', '7.19', $$Su ürünleri işleme tesisleri$$, 131),
('ek2', '7.20.1', $$Kesimhane: 10 büyükbaş - 100 büyükbaş arası kesim/gün$$, 132),
('ek2', '7.20.2', $$Kesimhane: 1.000 tavuk - 50.000 tavuk arası kesim/gün$$, 133),
('ek2', '7.21', $$Kültür balıkçılığı karada su temini ile (Kapasite >= 5 ton/yıl)$$, 134),
('ek2', '7.22', $$Konserve ve ambalajlama (Bitkisel/hayvansal, 3 ton/gün - 100 ton/gün)$$, 135),
('ek2', '8.1.1', $$Toplama-ayırma tesisleri (1, 2, 3. Tip)$$, 136),
('ek2', '8.1.2', $$Gemi geri dönüşüm tesisleri$$, 137),
('ek2', '8.1.3', $$Hurda metal ve ömrünü tamamlamış araç işleme$$, 138),
('ek2', '8.2.1', $$Tehlikesiz atık geri kazanım (plastik, cam, ahşap, kompozit vb.)$$, 139),
('ek2', '8.2.2', $$Tehlikesiz atık geri kazanım: Kâğıt (< 300 ton/gün)$$, 140),
('ek2', '8.2.3', $$Tehlikesiz atık geri kazanım: Metal ergitme (< 2.000 ton/gün)$$, 141),
('ek2', '8.3.1', $$Bitkisel atık yağ ara depolama tesisleri$$, 142),
('ek2', '8.3.2', $$Atık yağ transfer noktaları$$, 143),
('ek2', '8.3.3', $$Atık akümülatör ara depolama tesisleri$$, 144),
('ek2', '8.3.4', $$Ömrünü tamamlamış lastik ara depolama tesisleri$$, 145),
('ek2', '8.3.5', $$Gemi atık kabul tesisleri$$, 146),
('ek2', '8.3.6', $$Tanker temizleme tesisleri$$, 147),
('ek2', '8.3.7', $$Atık elektrikli ve elektronik eşya transfer noktaları$$, 148),
('ek2', '9.1.1', $$Sıvılaştırılmış petrol gazı depolama (200 m3 - 10.000 m3 arası)$$, 149),
('ek2', '9.1.2', $$Doğalgaz/LNG depolama (1.000 m3 - 20.000 m3 arası)$$, 150),
('ek2', '9.1.3', $$LPG tüp dolum işlemleri (30 ton/gün - 200 ton/gün)$$, 151),
('ek2', '9.2.1', $$Ham petrol depolama (5.000 ton - 100.000 ton)$$, 152),
('ek2', '9.2.2', $$Akaryakıt depolama (Benzin, motorin vb, 1.000 ton - 50.000 ton)$$, 153),
('ek2', '9.2.3', $$Organik kimyasal madde depolama (200 ton - 50.000 ton)$$, 154),
('ek2', '9.3', $$Akrilonitril depolama (200 ton - 2.000 ton)$$, 155),
('ek2', '9.4', $$Kükürt dioksit depolama (Kapasite >= 20 ton)$$, 156),
('ek2', '9.5', $$Bitki koruma ve/veya biyosidal ürün depolama (Kapasite >= 5 ton)$$, 157),
('ek2', '9.6', $$Tozuma yapan maddelerin doldurulup boşaltıldığı açık/yarı kapalı depolar (>= 200 ton/gün)$$, 158),
('ek2', '10.1', $$Patlama tehlikesi olan maddelerin üretildiği tesisler$$, 159),
('ek2', '10.2', $$Kentsel/evsel atıksu arıtma (Kapasite < 20.000 m3/gün)$$, 160),
('ek2', '10.3', $$3.000 KW ve üzeri jet motorlar/gaz türbinleri test merkezleri$$, 161),
('ek2', '10.4', $$Sigara fabrikaları ve tütün işleme (Kapasite >= 1.000 ton/yıl)$$, 162),
('ek2', '10.5', $$Limanlar ve yat limanları$$, 163),
('ek2', '10.6', $$Turizm konaklama tesisleri (Yatak Kapasitesi >= 200)$$, 164),
('ek2', '10.7', $$Hastane ve sağlık kuruluşları (Yatak >= 20) veya >= 15 cihazlık diyaliz/diş sağlığı merkezleri$$, 165),
('ek2', '10.8', $$Alıcı ortama atıksu deşarjı olan diğer listesiz tesisler$$, 166);
