export interface PermitArticle {
  code: string;
  title: string;
}

export const EK1_ARTICLES: PermitArticle[] = [
  { code: "1.1", title: "Toplam yakma sistemi ısıl gücü 100 MW ve daha fazla olan termik ve ısı santralleri" },
  { code: "1.2.1", title: "Toplam yakma sistemi ısıl gücü 100 MW ve daha fazla olan ve yakıt olarak katı, sıvı, gaz yakıt ve biyokütlenin kullanıldığı tesisler" },
  { code: "1.2.2", title: "Toplam yakma sistemi ısıl gücü 50 MW ve daha fazla olan ve yakıt olarak katı ve sıvı yanıcı maddelerin kullanıldığı tesisler" },
  { code: "1.3", title: "Toplam yakma sistemi ısıl gücü 100 MW ve daha fazla olan kombine çevrim, birleşik ısı güç santralleri, içten yanmalı motorlar, gaz türbinleri, jeneratörler" },
  { code: "1.4", title: "Nükleer güç santralleri" },
  { code: "1.5", title: "Katran, katran ürünleri ve doğal asfalt üretim ve işleme tesisleri" },
  { code: "1.6", title: "Parçalama yoluyla hidrokarbonlardan gaz yakıt üretim tesisleri" },
  { code: "1.7.1", title: "Ham petrol rafinerileri" },
  { code: "1.7.2", title: "Hammadde kapasitesi 500 ton/gün ve daha fazla olan taşkömürü ve/veya bitümlü maddeleri gazlaştırma ve/veya sıvılaştırma tesisleri" },
  { code: "1.7.3", title: "Doğalgaz sıvılaştırma ve/veya gazlaştırma tesisleri" },
  { code: "1.8", title: "Kok üretim tesisleri" },
  { code: "1.9", title: "500 ton/gün ve daha fazla ham petrol ve/veya 500.000 m3/gün ve daha fazla doğalgaz çıkarılması işlemleri" },
  
  { code: "2.1", title: "Entegre çimento üretim tesisleri ve/veya çimento klinkeri üretim tesisleri" },
  { code: "2.2", title: "Yakıt olarak petrol koku kullanan ve sönmemiş ürün üretim kapasitesi 250 ton/gün ve üzeri olan boksit, dolomit, alçıtaşı, kireçtaşı, kiselgur, magnezit, kuvars ve/veya şamot pişirme tesisleri" },
  { code: "2.3", title: "Asbestos ve asbestos içeren ürünlerin çıkarıldığı, üretildiği ve/veya işlendiği tesisler" },
  { code: "2.4", title: "Toplam eritme kapasitesi 300 ton/gün ve daha fazla olan cam, glasswool ve/veya cam elyaf üretim tesisleri" },
  { code: "2.5", title: "Üretim kapasitesi 300 ton/gün ve daha fazla olan seramik ve/veya porselen üretim tesisleri" },
  
  { code: "3.1", title: "Metal ve kükürt cevherlerinin kavrulması, ergitilmesi, sinterlemesi, peletlemesi işlemlerinden en az birini içeren tesisler" },
  { code: "3.2", title: "Cevherden demir ve/veya çelik üreten tesisler" },
  { code: "3.3", title: "Üretim kapasitesi 100 ton/gün ve daha fazla olan cevherden, konsantreden ve/veya ikincil hammaddeden demir içermeyen ham metal üretim tesisleri" },
  { code: "3.4", title: "Üretim kapasitesi 500 ton/gün ve daha fazla olan ham demir üretim tesisleri" },
  { code: "3.5", title: "Üretim kapasitesi 2.000 ton/gün ve daha fazla olan ikincil metal özelliğine sahip demir-çelik hammaddesinden çelik üreten tesisler" },
  { code: "3.6", title: "Üretim kapasitesi 50 ton/gün ve daha fazla olan demir dışı metallerin ergitildiği ve/veya döküldüğü tesisler" },
  { code: "3.7.1", title: "Sıcak Haddeleme: Üretim kapasitesi 5.000 ton/gün ve daha fazla olan demir ve/veya çeliğin haddelendiği tesisler" },
  { code: "3.7.2", title: "Sıcak Haddeleme: Üretim kapasitesi 250 ton/gün ve daha fazla olan demir dışı metallerin haddelendiği tesisler" },
  { code: "3.8", title: "Üretim kapasitesi 700 ton/gün ve daha fazla olan demir, temper ve/veya çelik dökümhaneleri" },
  { code: "3.9", title: "Üretim kapasitesi 5.000 adet/gün ve daha fazla olan kurşunlu akümülatör ve/veya hücre üretimi dahil olmak üzere endüstriyel akümülatör üretimi yapan tesisler" },
  
  { code: "4.1.1", title: "Toplam üretim kapasitesi 150 ton/gün ve daha fazla olan inorganik kimyasal maddelerin üretildiği tesisler" },
  { code: "4.1.2", title: "İnorganik gazların üretildiği tesisler" },
  { code: "4.1.3", title: "Üretim kapasitesi 50 ton/gün ve daha fazla olan azot, fosfor, potasyum bazlı ve/veya organik gübre üretim tesisleri" },
  { code: "4.1.4", title: "Toplam üretim kapasitesi 50 ton/gün ve daha fazla olan organik kimyasalların üretildiği tesisler ve/veya petrokimya tesisleri" },
  { code: "4.2", title: "Organik kimyasal maddelerin hammadde olarak kullanım kapasitesi 100 ton/gün ve daha fazla olan tesisler" },
  { code: "4.3", title: "Toplam üretim kapasitesi 3.000 ton/yıl ve daha fazla olan ve terbiye işlemlerinden en az birini içeren iplik, kumaş, halı ve benzeri fabrikaları" },
  { code: "4.4", title: "Üretim kapasitesi 2.000 ton/yıl ve daha fazla olan ham deri işleme tesisleri" },
  { code: "4.5", title: "Toplam üretim kapasitesi 100 ton/gün ve daha fazla olan boya, pigment, vernik, cila ve benzeri maddelerin üretildiği tesisler" },
  
  { code: "5.1", title: "Toplam organik çözücü içeriği 250 kg/saat ve daha fazla olan boya, cila ve benzeri maddelerle malzemelerin boyandığı, cilalandığı ve/veya kurutulduğu tesisler" },
  { code: "5.2", title: "Toplam organik çözücü içeriği 250 kg/saat ve daha fazla olan boya ve benzeri maddeler kullanarak malzemelerin döner baskı makinaları ile basıldığı ve/ve/veya kurutulduğu tesisler" },
  { code: "5.3", title: "Üretim kapasitesi 10.000 adet/yıl ve daha fazla olan motorlu taşıtların üretildiği ve/veya boyandığı tesisler" },
  { code: "5.4", title: "Üretim kapasitesi 1.000 adet/yıl ve daha fazla olan demiryolu taşıtlarının üretildiği ve/veya boyandığı tesisler" },
  { code: "5.5", title: "Motorlu hava taşıtlarının üretildiği ve/veya onarımının yapıldığı tesisler" },
  
  { code: "6.1", title: "Selüloz üretim tesisleri" },
  { code: "6.2", title: "Kereste ve/veya benzeri lifli maddelerden kâğıt hamuru üretim tesisleri" },
  { code: "6.3", title: "Toplam üretim kapasitesi 300 ton/gün ve daha fazla olan ve hammadde olarak hazır selüloz ve/veya kâğıt kullanarak her çeşit karton, kâğıt ve/veya mukavva üretimi yapan tesisler" },
  
  { code: "7.1", title: "Şeker üretim tesisleri" },
  { code: "7.2", title: "Üretim kapasitesi 30 ton/gün ve daha fazla olan zeytin işleme tesisleri" },
  { code: "7.3.1", title: "Yağlı tohum işleme kapasitesi 1.000 ton/gün ve daha fazla olan ham yağ üretim tesisleri" },
  { code: "7.3.2", title: "Üretim kapasitesi 200 ton/gün ve daha fazla olan bitkisel yağ rafinasyon tesisleri" },
  { code: "7.4", title: "Üretim kapasitesi 25.000 ton/yıl ve daha fazla olan maya üretim tesisleri" },
  { code: "7.5", title: "Üretim kapasitesi 50.000 m3/yıl ve daha fazla olan fermantasyon ile alkollü içecek üreten tesisler" },
  { code: "7.6.1", title: "Toplam 5.000 büyükbaş eşdeğeri ve daha fazla sayıda hayvan yetiştiriciliği yapan tesisler" },
  { code: "7.6.2", title: "Toplam 1000 baş ve daha fazla sayıda domuz besiciliği yapan tesisler" },
  { code: "7.6.3", title: "Toplam 60.000 adet tavuk eşdeğeri ve daha fazla sayıda kanatlı hayvan yetiştiriciliği yapan tesisler" },
  { code: "7.7.1", title: "Toplam 100 büyükbaş eşdeğeri/gün ve daha fazla hayvan kesiminin yapıldığı tesisler" },
  { code: "7.7.2", title: "Toplam 50.000 adet tavuk eşdeğeri/gün ve daha fazla kanatlı hayvan kesiminin yapıldığı tesisler" },
  { code: "7.8", title: "Hammadde kapasitesi 100.000 litre/gün ve daha fazla olan süt ürünleri üretim tesisleri" },
  { code: "7.9", title: "Üretim kapasitesi 100 ton/gün ve daha fazla olan, bitkisel ve/veya hayvansal ürünlerin işlendiği, konserve yapıldığı ve/veya ambalajlandığı tesisler" },
  
  { code: "8.1.1", title: "Tıbbi atık sterilizasyon tesisleri" },
  { code: "8.1.2", title: "Atık elektrikli ve elektronik eşya işleme tesisleri" },
  { code: "8.1.3", title: "Atıktan türetilmiş yakıt (ATY) hazırlama tesisleri" },
  { code: "8.1.4", title: "PCB arındırma tesisleri" },
  { code: "8.1.5", title: "Ömrünü tamamlamış araç geçici depolama tesisleri" },
  { code: "8.1.6", title: "Tehlikeli atık ön işlem tesisleri" },
  { code: "8.1.7", title: "Tehlikesiz atık ön işlem tesisleri" },
  { code: "8.2.1", title: "Biyobozunur atık geri kazanım tesisleri (Mekanik ayırma, Biyokurutma, Biyometanizasyon, Kompost)" },
  { code: "8.2.2", title: "Atık yağ rafinasyon tesisleri" },
  { code: "8.2.3", title: "Bitkisel atık yağ geri kazanım tesisleri" },
  { code: "8.2.4", title: "Atık pil ve akümülatör geri kazanım tesisleri" },
  { code: "8.2.5", title: "Ömrünü tamamlamış lastik geri kazanım tesisleri" },
  { code: "8.2.6", title: "Tehlikeli atık geri kazanım tesisleri" },
  { code: "8.2.7.1", title: "Geri kazanım: Kapasitesi 300 ton/gün ve üzeri kâğıt geri kazanım tesisleri" },
  { code: "8.2.7.2", title: "Geri kazanım: Kapasitesi 2.000 ton/gün ve üzeri metal geri kazanım/ergitme tesisleri" },
  { code: "8.2.7.3", title: "Diğer tehlikesiz atık geri kazanım tesisleri" },
  { code: "8.2.8", title: "İleri Termal İşlem Tesisi (Piroliz, Gazlaştırma vb.)" },
  { code: "8.3.1.1", title: "Düzenli Depolama I. Sınıf" },
  { code: "8.3.1.2", title: "Düzenli Depolama II. Sınıf" },
  { code: "8.3.1.3", title: "Düzenli Depolama III. Sınıf" },
  { code: "8.3.2", title: "Maden atığı bertaraf tesisleri" },
  { code: "8.4.1", title: "Atık yakma ve/veya beraber yakma tesisleri" },
  { code: "8.4.2", title: "Atık ara depolama tesisleri" },
  { code: "8.4.3", title: "Yeniden Kullanıma Hazırlama tesisleri" },
  { code: "8.4.4", title: "Atık elektrikli ve elektronik eşya yeniden kullanıma hazırlama tesisi" },
  
  { code: "9.1.1", title: "Sıvılaştırılmış petrol gazı depolama (Kapasite >= 10.000 m3)" },
  { code: "9.1.2", title: "Doğalgaz/LNG depolama (Kapasite >= 20.000 m3)" },
  { code: "9.1.3", title: "LPG tüp dolum işlemleri (Kapasite >= 200 ton/gün)" },
  { code: "9.2.1", title: "Ham petrol depolama (Kapasite >= 100.000 ton)" },
  { code: "9.2.2", title: "Akaryakıt depolama (Benzin, motorin vb. Kapasite >= 50.000 ton)" },
  { code: "9.2.3", title: "Organik kimyasal madde depolama (Kapasite >= 50.000 ton)" },
  { code: "9.3", title: "Akrilonitril depolama (Kapasite >= 2.000 ton)" },
  
  { code: "10.1", title: "Sanayilerin toplu olarak yer aldığı bölgelere ait ortak atıksu arıtma tesisleri" },
  { code: "10.2", title: "Kentsel/evsel atıksu arıtma (Kapasite >= 20.000 m3/gün)" }
];

export const EK2_ARTICLES: PermitArticle[] = [
  { code: "1.1.1", title: "Termik/Isı Santralleri: 1 MW - 100 MW arası katı/sıvı yakıtlı tesisler" },
  { code: "1.1.2", title: "Termik/Isı Santralleri: 2 MW - 100 MW arası gaz yakıtlı veya çok yakıtlı tesisler" },
  { code: "1.2.1", title: "Yakıt yakan tesisler: 1 MW - 100 MW arası katı, sıvı yakıt ve biyokütle yakan tesisler" },
  { code: "1.2.2", title: "Yakıt yakan tesisler: 2 MW - 100 MW arası gaz ve çok yakıtlı tesisler" },
  { code: "1.2.3", title: "Yakıt yakan tesisler: 1 MW - 50 MW arası katı/sıvı yanıcı madde yakan tesisler" },
  { code: "1.3", title: "Kombine çevrim, jeneratörler vb: 1 MW - 100 MW arası tesisler" },
  { code: "1.4", title: "Kömür gazlaştırma/sıvılaştırma tesisleri (10 ton/gün - 500 ton/gün)" },
  { code: "1.5", title: "500 ton/gün'den az ham petrol veya 500.000 m3/gün'den az doğalgaz çıkarılması" },
  { code: "1.6", title: "Kurulu gücü 5MWe ve üzerinde olan jeotermal enerji üretim tesisleri" },
  
  { code: "2.1", title: "Klinkerden çimento üreten ve/veya paketleyen tesisler" },
  { code: "2.2", title: "Petrol koku yakan kireç/dolomit vb. pişirme tesisleri (< 250 ton/gün)" },
  { code: "2.3", title: "Petrol koku dışı yakıt yakan kireç/dolomit vb. pişirme tesisleri" },
  { code: "2.4", title: "Kireç, alçı, talk, kil vb. öğütme, söndürme ve/veya paketleme tesisleri" },
  { code: "2.5", title: "Perlit, zeolit, şist ve/veya kil genleştirme tesisleri" },
  { code: "2.6", title: "Cam, cam elyaf ve/veya cam yünü üretimi (< 300 ton/gün)" },
  { code: "2.7", title: "Cam ve cam ürünlerini asitlerle parlatan ve/veya matlaştıran tesisler" },
  { code: "2.8", title: "Seramik ve/veya porselen üretimi (3 ton/gün - 300 ton/gün)" },
  { code: "2.9", title: "Tuğla, ateş tuğlası ve/veya kiremit üretimi (>= 75 ton/gün)" },
  { code: "2.10", title: "Mineral madde ergitme tesisleri (Hammadde >= 20 ton/gün)" },
  { code: "2.11", title: "Gazlı beton, beton elemanı, çimento esaslı levha üretim tesisleri" },
  { code: "2.12", title: "Hazır beton ve harç tesisleri (Kapasite >= 10 m3/saat)" },
  { code: "2.13", title: "Beton/çimento esaslı sıkıştırılmış şekilli malzeme üretimi (>= 5 ton/saat)" },
  { code: "2.14", title: "Asfalt plent tesisleri ve mineral malzeme katkılı bitüm tesisleri" },
  { code: "2.15", title: "Patlayıcı kullanılan maden ve/veya taş ocakları" },
  { code: "2.16", title: "Maden ocakları (Maden Kanunu I, II, IV, V Grup, Kapasite >= 150 ton/gün)" },
  { code: "2.17", title: "Maden kırma, eleme, öğütme tesisleri (Kapasite >= 150 ton/gün)" },
  { code: "2.18", title: "Mermer işleme tesisleri (Kapasite >= 25.000 ton/yıl)" },
  { code: "2.19", title: "Kömür ve/veya cevher hazırlama ve/veya zenginleştirme tesisleri" },
  { code: "2.20", title: "Tuz üretim tesisleri" },
  
  { code: "3.1", title: "Demir dışı ham metal üretimi (15 ton/gün - 100 ton/gün)" },
  { code: "3.2", title: "Ham demir üretimi (50 ton/gün - 500 ton/gün)" },
  { code: "3.3", title: "İkincil metalden çelik üreten tesisler (< 2.000 ton/gün)" },
  { code: "3.4", title: "Demir dışı metal ergitme/döküm tesisleri (100 kg/gün - 50 ton/gün)" },
  { code: "3.5.1", title: "Sıcak Haddeleme: Demir/çelik haddeleme (5 ton/gün - 5.000 ton/gün)" },
  { code: "3.5.2", title: "Sıcak Haddeleme: Demir dışı metal haddeleme (5 ton/gün - 250 ton/gün)" },
  { code: "3.5.3", title: "Haddelemesiz metal ısıl işlem fırınları (Kapasite >= 5 ton/gün)" },
  { code: "3.6.1", title: "Soğuk Haddeleme: Demir/çelik (Kapasite >= 10 ton/gün)" },
  { code: "3.6.2", title: "Soğuk Haddeleme: Demir dışı metal (Kapasite >= 5 ton/gün)" },
  { code: "3.7", title: "Demir, temper ve çelik dökümhaneleri (5 ton/gün - 700 ton/gün)" },
  { code: "3.8", title: "Kurşunlu akümülatör/hücre üretimi (< 5.000 adet/gün)" },
  { code: "3.9", title: "Metal/plastik yüzey elektrolitik veya kimyasal kaplama (Havuz Hacmi >= 5 m3)" },
  { code: "3.10", title: "Batarya ve/veya pil üreten tesisler" },
  { code: "3.11", title: "Metal kaplama (Kurşun, çinko vb ergitme/püskürtme, Kapasite >= 5 ton/gün)" },
  { code: "3.12", title: "Metallerin sıcak dövüldüğü tesisler (Pres gücü >= 100 ton)" },
  { code: "3.13", title: "Civata, çivi vb soğuk/sıcak şekillendirme metal üretimi (>= 10 ton/gün)" },
  { code: "3.14", title: "Patlayıcı madde ile detonasyonlu biçimlendirme ve kaynak işleri" },
  { code: "3.15", title: "Metal sac depolama deposu, tank, makina üretimi (Kapasite >= 3 ton/gün)" },
  { code: "3.16", title: "Çelik boru ve profil üretimi (Soğuk/sıcak şekillendirme)" },
  { code: "3.17", title: "Metal püskürtmeli temizleme, taşlama, zımparalama (>= 10 ton/gün)" },
  { code: "3.18", title: "Metal tozları ve pastaları üreten tesisler" },
  { code: "3.19", title: "Motorlu taşıtların motorlarının üretimi" },
  { code: "3.20", title: "Tersaneler (Gemi inşa/bakım-onarım veya >= 20 m yat/tekne inşa/bakım)" },
  { code: "3.21", title: "Uçak bakım ve/veya onarım tesisleri" },
  { code: "3.22", title: "Demiryolu ekipmanı üreten tesisler" },
  { code: "3.23", title: "Metallere sırlama, emaye, mineleme ve benzeri işlemler" },
  { code: "3.24", title: "Demir dışı metal oksit üretim tesisleri" },
  
  { code: "4.1.1", title: "İnorganik kimyasal madde üretimi (< 150 ton/gün)" },
  { code: "4.1.2", title: "Hidrometalürji/elektrometalürji ile metal üretimi" },
  { code: "4.1.3", title: "Kalsiyum karpit, bor, silisyum karpit vb inorganik madde üretimi" },
  { code: "4.1.4", title: "İnorganik halojenli bileşiklerin üretildiği tesisler" },
  { code: "4.1.5", title: "Asetilen gazı üretim tesisleri" },
  { code: "4.1.6", title: "Organik kimyasal/petrokimya üretimi (1 ton/gün - 50 ton/gün)" },
  { code: "4.1.7", title: "Organometalik bileşiklerin üretildiği tesisler" },
  { code: "4.1.8.1", title: "Polimer ve sentetik elyaf üretim tesisleri" },
  { code: "4.1.8.2", title: "Sentetik reçine üretim tesisleri" },
  { code: "4.1.8.3", title: "Sentetik kauçuk veya kauçuk hamuru üretim tesisleri" },
  { code: "4.1.8.4", title: "Selüloz nitrat ve selüloit üretim tesisleri" },
  { code: "4.1.9", title: "Yüzey aktif maddelerin üretildiği tesisler" },
  { code: "4.1.10", title: "Kauçuk vulkanize lastik üretimi (Kapasite >= 50 kg/saat)" },
  { code: "4.1.11", title: "Lastik rejenere eden tesisler (Hammadde >= 3 ton/gün)" },
  { code: "4.1.12", title: "Katran boyası ve boya ara ürünleri üretim tesisleri" },
  { code: "4.1.13", title: "Temizlik ve bakım ürünleri üretimi (Kapasite >= 2 ton/gün)" },
  { code: "4.1.14", title: "Azot, fosfor, potasyum ve organik gübre üretimi (< 50 ton/gün)" },
  { code: "4.2", title: "Organik kimyasal hammadde kullanımı (2 ton/gün - 100 ton/gün)" },
  { code: "4.3", title: "Bitki koruma, biyosidal ürün veya etken maddesi üretimi" },
  { code: "4.4", title: "Farmasotik (ilaç vb) ürünlerin üretildiği tesisler" },
  { code: "4.5", title: "Yağlayıcı maddeler, gres yağları üretimi" },
  { code: "4.6", title: "Karbon siyahı, sentetik grafit üretimi" },
  { code: "4.7", title: "Doğal/sentetik reçine bazlı ürün üretimi (Reçine kullanımı >= 25 kg/saat)" },
  { code: "4.8", title: "Boya, pigment, vernik üretimi (1 ton/gün - 100 ton/gün)" },
  { code: "4.9", title: "Sentetik kauçuk bazlı ürünler üreten tesisler" },
  { code: "4.10", title: "Nitroselüloz ile vernik, mürekkep vb üretimi" },
  { code: "4.11", title: "Sülfat terebentin yağı veya tall yağı üretimi/işlenmesi" },
  { code: "4.12", title: "Yapı ve ahşap koruma/yapıştırma maddeleri üretimi (Kapasite >= 1 ton/gün)" },
  { code: "4.13", title: "İplik, kumaş terbiye fabrikaları (< 3.000 ton/yıl)" },
  { code: "4.14", title: "Ham deri işleme tesisleri (< 2.000 ton/yıl)" },
  { code: "4.15", title: "Biyodizel üretim tesisleri (Kapasite >= 1 ton/gün)" },
  { code: "4.16", title: "Zifir üretim ve zift buharlaştırma tesisleri" },
  { code: "4.17", title: "Plastik hammaddeler kullanarak plastik ürünler üreten tesisler" },
  { code: "4.18", title: "Diğer kimyasalların işlendiği tanımlanmayan tesisler" },
  
  { code: "5.1", title: "Yüzey boyama/kurutma: Çözücü kullanımı (25 kg/saat - 250 kg/saat)" },
  { code: "5.2", title: "Döner baskı boyama/kurutma: Çözücü kullanımı (25 kg/saat - 250 kg/saat)" },
  { code: "5.3", title: "Reçineli emprenye/kaplama/doyurma vb. (Kullanım >= 25 kg/saat)" },
  { code: "5.4", title: "Motorlu taşıt üretimi/boyanması (500 adet/yıl - 10.000 adet/yıl)" },
  { code: "5.5", title: "Demiryolu taşıt üretimi/boyanması (< 1.000 adet/yıl)" },
  { code: "5.6", title: "Beyaz eşya üretimi (Kapasite >= 10 ton/gün)" },
  { code: "5.7", title: "Malzemelerin katran, bitüm vb sıcak kaplanması" },
  { code: "5.8", title: "Tellerin organik maddeyle izole edilmesi" },
  { code: "5.9", title: "Sıvı/doymamış polyester reçine işleme (Kapasite >= 500 kg/saat)" },
  { code: "5.10", title: "Furan, fenolik veya aminoplast reçinelerin işlenmesi (Hammadde >= 10 kg/saat)" },
  { code: "5.11", title: "Sentetik reçine kullanarak balata üretimi" },
  { code: "5.12", title: "Zımpara kağıdı, plakası üretimi (Organik çözücü/bağlayıcı ile)" },
  { code: "5.13", title: "Plastik genleştirme, hacim verme (Hammadde >= 1.000 kg/saat)" },
  { code: "5.14", title: "Elektrostatik toz boyama (Kullanım >= 50 kg/saat)" },
  
  { code: "6.1", title: "Parke, sunta vb levha üretimi (Kapasite >= 500 m3/yıl)" },
  { code: "6.2", title: "Ağaç işleme ve kereste üretimi (Kapasite >= 3.500 m3/yıl)" },
  { code: "6.3", title: "Mobilya/ahşap ürün üretimi (Kapasite >= 150.000 m2/yıl)" },
  { code: "6.4", title: "Karton, kâğıt, mukavva üretimi (Kapasite < 300 ton/gün)" },
  
  { code: "7.1", title: "Süt ürünleri üretimi (10.050 lt/gün - 100.000 lt/gün)" },
  { code: "7.2", title: "Suma ve/veya malt üretimi (Kapasite >= 1.000 m3/yıl)" },
  { code: "7.3", title: "Alkollü içecek fermantasyon üretimi (50 m3/yıl - 50.000 m3/yıl)" },
  { code: "7.4", title: "Alkolsüz içecek üretimi (Kapasite >= 50 m3/yıl)" },
  { code: "7.5", title: "Şekerleme, çikolata üretimi (Kapasite >= 5 ton/gün)" },
  { code: "7.6", title: "Hayvansal yağların ergitilmesi (Kapasite >= 30 kg/gün)" },
  { code: "7.7", title: "Hayvansal artıkların depolanması ve işlenmesi" },
  { code: "7.8", title: "Hayvan derisi/kılı depolama ve işleme" },
  { code: "7.9", title: "Balık yağı, balık unu depolama ve üretimi" },
  { code: "7.10.1", title: "Zeytin işleme (Kapasite 1 ton/gün - 30 ton/gün)" },
  { code: "7.10.2", title: "Zeytinyağı üretimi (Kapasite >= 30 ton/gün)" },
  { code: "7.11.1", title: "Bitkisel ham yağ üretimi (< 1.000 ton/gün)" },
  { code: "7.11.2", title: "Bitkisel yağ rafinasyonu (< 200 ton/gün)" },
  { code: "7.12", title: "Çay üretimi (Kapasite >= 100 kg/gün)" },
  { code: "7.13", title: "Maya üretimi (< 25.000 ton/yıl)" },
  { code: "7.14", title: "Süt tozu üretim tesisleri" },
  { code: "7.15", title: "Nişasta ve nişasta türevleri üretimi" },
  { code: "7.16", title: "Hayvan yemi/dışkısı kurutma tesisleri" },
  { code: "7.17.1", title: "Büyükbaş hayvancılık (500 büyükbaş - 5.000 büyükbaş)" },
  { code: "7.17.2", title: "Domuz besiciliği (< 1.000 baş)" },
  { code: "7.17.3", title: "Kanatlı hayvancılık (20.000 tavuk - 60.000 tavuk)" },
  { code: "7.18", title: "Sıvı yumurta üretimi (Kapasite >= 10 ton/gün)" },
  { code: "7.19", title: "Su ürünleri işleme tesisleri" },
  { code: "7.20.1", title: "Kesimhane: 10 büyükbaş - 100 büyükbaş arası kesim/gün" },
  { code: "7.20.2", title: "Kesimhane: 1.000 tavuk - 50.000 tavuk arası kesim/gün" },
  { code: "7.21", title: "Kültür balıkçılığı karada su temini ile (Kapasite >= 5 ton/yıl)" },
  { code: "7.22", title: "Konserve ve ambalajlama (Bitkisel/hayvansal, 3 ton/gün - 100 ton/gün)" },
  
  { code: "8.1.1", title: "Toplama-ayırma tesisleri (1, 2, 3. Tip)" },
  { code: "8.1.2", title: "Gemi geri dönüşüm tesisleri" },
  { code: "8.1.3", title: "Hurda metal ve ömrünü tamamlamış araç işleme" },
  { code: "8.2.1", title: "Tehlikesiz atık geri kazanım (plastik, cam, ahşap, kompozit vb.)" },
  { code: "8.2.2", title: "Tehlikesiz atık geri kazanım: Kâğıt (< 300 ton/gün)" },
  { code: "8.2.3", title: "Tehlikesiz atık geri kazanım: Metal ergitme (< 2.000 ton/gün)" },
  { code: "8.3.1", title: "Bitkisel atık yağ ara depolama tesisleri" },
  { code: "8.3.2", title: "Atık yağ transfer noktaları" },
  { code: "8.3.3", title: "Atık akümülatör ara depolama tesisleri" },
  { code: "8.3.4", title: "Ömrünü tamamlamış lastik ara depolama tesisleri" },
  { code: "8.3.5", title: "Gemi atık kabul tesisleri" },
  { code: "8.3.6", title: "Tanker temizleme tesisleri" },
  { code: "8.3.7", title: "Atık elektrikli ve elektronik eşya transfer noktaları" },
  
  { code: "9.1.1", title: "Sıvılaştırılmış petrol gazı depolama (200 m3 - 10.000 m3 arası)" },
  { code: "9.1.2", title: "Doğalgaz/LNG depolama (1.000 m3 - 20.000 m3 arası)" },
  { code: "9.1.3", title: "LPG tüp dolum işlemleri (30 ton/gün - 200 ton/gün)" },
  { code: "9.2.1", title: "Ham petrol depolama (5.000 ton - 100.000 ton)" },
  { code: "9.2.2", title: "Akaryakıt depolama (Benzin, motorin vb, 1.000 ton - 50.000 ton)" },
  { code: "9.2.3", title: "Organik kimyasal madde depolama (200 ton - 50.000 ton)" },
  { code: "9.3", title: "Akrilonitril depolama (200 ton - 2.000 ton)" },
  { code: "9.4", title: "Kükürt dioksit depolama (Kapasite >= 20 ton)" },
  { code: "9.5", title: "Bitki koruma ve/veya biyosidal ürün depolama (Kapasite >= 5 ton)" },
  { code: "9.6", title: "Tozuma yapan maddelerin doldurulup boşaltıldığı açık/yarı kapalı depolar (>= 200 ton/gün)" },
  
  { code: "10.1", title: "Patlama tehlikesi olan maddelerin üretildiği tesisler" },
  { code: "10.2", title: "Kentsel/evsel atıksu arıtma (Kapasite < 20.000 m3/gün)" },
  { code: "10.3", title: "3.000 KW ve üzeri jet motorlar/gaz türbinleri test merkezleri" },
  { code: "10.4", title: "Sigara fabrikaları ve tütün işleme (Kapasite >= 1.000 ton/yıl)" },
  { code: "10.5", title: "Limanlar ve yat limanları" },
  { code: "10.6", title: "Turizm konaklama tesisleri (Yatak Kapasitesi >= 200)" },
  { code: "10.7", title: "Hastane ve sağlık kuruluşları (Yatak >= 20) veya >= 15 cihazlık diyaliz/diş sağlığı merkezleri" },
  { code: "10.8", title: "Alıcı ortama atıksu deşarjı olan diğer listesiz tesisler" }
];
